### ISSUE TITLE
Does this work with DNS API v2?

### ISSUE THREAD

**Issue by nameduser0** [mythic-beasts/dehydrated-mythic-dns01#14]
Could you make it clear if this works with DNS API v2 please?
The documentation links to the [Mythic Beasts guide](https://www.mythic-beasts.com/support/domains/letsencrypt_dns_01) which describes adding an APIv1 key. It's not clear if v2 should work or not.

**Comment by dafyddj** [comment]
The latest blog [post (5/5/2020)](https://www.mythic-beasts.com/blog/2020/05/05/automating-dns-challenges/) on this topic says:

> Our preferred Let’s Encrypt client is the excellent dehydrated, and we maintain a hook script for supporting DNS-based challenges in dehydrated. **We haven’t yet updated the hook script to support our new API**, but will be doing so soon and will post details here when it’s ready.

and there have been no commits since that date.

**Comment by nameduser0** [comment]
Thanks, I actually wrote my own hook script for the Mythic v2 API in the end. Comment here if you'd like me to share it..

**Comment by dafyddj** [comment]
That would be handy, thanks.

**Comment by pdw-mb** [comment]
We've not yet made a start on our own implementation so it'd be very useful to see your code - a PR would be even more welcome :-)

**Comment by nameduser0** [comment]
Okay, might take me a while to get back to my laptop but will put it in a gist/repo and post here. It's nothing spectacular, a single shell script, I wouldn't have the time to integrate it..

**Comment by nameduser0** [comment]
Well that took a bit longer than expected... 😱
[Hook script gist](https://gist.github.com/casesolved-co-uk/cd9265dc0d1a27b7355671c113484d8d)

**Comment by nameduser0** [comment]
Now updated to cope with multiple challenges at once
[gist](https://gist.github.com/casesolved-co-uk/cd9265dc0d1a27b7355671c113484d8d)

**Comment by paulwarren-wk** [comment]
DNS API v2 support was merged last year.  Closing this issue.

**Comment by pdw-mb** [comment]
DNS API v2 support was merged last year. Closing this issue.
